#include "core.hpp"
#include "google_drive.hpp"
#include "httplib.h"
#include <iostream>
#include <thread>
#include <mutex>
#include <atomic>
using cxs::Json;using cxs::Bytes;namespace fs=std::filesystem;
static void check(bool value,const char* message){if(!value)throw std::runtime_error(message);}
static Bytes encoded(const Json& value){auto text=value.dump();return {text.begin(),text.end()};}
class Fixture {
public:
    Json files=Json::object();std::mutex mutex;httplib::Server server;std::jthread worker;
    std::string origin,account="visible-account";std::atomic<size_t> next{0},uploads{0},downloads{0},folders{0};std::atomic<bool> fail_snapshots{false};
    Fixture(){server.new_task_queue=[](){return new httplib::ThreadPool(8);};
        server.Post("/token",[](const auto&,auto& out){out.set_content(Json{{"access_token","visible-test"},{"token_type","Bearer"},{"expires_in",3600}}.dump(),"application/json");});
        server.Get("/drive/v3/about",[&](const auto&,auto& out){out.set_content(Json{{"user",{{"permissionId",account}}}}.dump(),"application/json");});
        server.Get("/drive/v3/files/generateIds",[&](const auto& in,auto& out){check(in.get_param_value("space")=="drive","visible IDs allocated in hidden space");Json ids=Json::array();for(int i=0;i<std::stoi(in.get_param_value("count"));++i)ids.push_back("visible"+std::to_string(++next));out.set_content(Json{{"ids",ids}}.dump(),"application/json");});
        server.Get("/drive/v3/files",[&](const auto& in,auto& out){check(in.get_param_value("spaces")=="drive","visible query used hidden space");const auto query=in.get_param_value("q");Json found=Json::array();std::lock_guard guard(mutex);
            for(const auto& [id,file]:files.items()){bool match=false;if(query.find("appProperties has")!=std::string::npos){for(const auto& [key,value]:file.at("appProperties").items())if(query.find("key='"+key+"'")!=std::string::npos&&query.find("value='"+value.get<std::string>()+"'")!=std::string::npos)match=true;}
                else{auto start=query.find("name = '");auto contains=query.find("name contains '");bool exact=start!=std::string::npos;start=exact?start+8:contains+15;auto end=query.find('\'',start);auto name=query.substr(start,end-start);auto full=file.at("name").get<std::string>();match=exact?full==name:full.find(name)!=std::string::npos;auto parent="'"+file.at("parent").get<std::string>()+"' in parents";match=match&&query.find(parent)!=std::string::npos;}
                if(match)found.push_back({{"id",id},{"name",file.at("name")}});}
            out.set_content(Json{{"files",found}}.dump(),"application/json");});
        server.Post("/drive/v3/files",[&](const auto& in,auto& out){Json file=Json::parse(in.body);check(file.at("mimeType")=="application/vnd.google-apps.folder","uncontrolled plaintext upload");auto id="visible"+std::to_string(++next);file["parent"]=file.value("parents",Json::array({"root"})).at(0);file["data"]="";{std::lock_guard guard(mutex);files[id]=file;}++folders;out.status=201;out.set_content(Json{{"id",id}}.dump(),"application/json");});
        server.Post("/upload/drive/v3/files",[&](const auto& in,auto& out){check(in.get_param_value("uploadType")=="multipart","unexpected fixture upload strategy");auto type=in.get_header_value("Content-Type");auto boundary=type.substr(type.find("boundary=")+9);auto first=in.body.find("\r\n\r\n"),split=in.body.find("\r\n--"+boundary+"\r\n",first+4);Json metadata=Json::parse(in.body.substr(first+4,split-first-4));auto body_start=in.body.find("\r\n\r\n",split+4),end=in.body.find("\r\n--"+boundary+"--\r\n",body_start+4);auto data=in.body.substr(body_start+4,end-body_start-4);check(data.starts_with("CXS"),"visible backup leaked plaintext");auto name=metadata.at("name").get<std::string>();if(fail_snapshots&&name.find(".snapshots.")!=std::string::npos){out.status=503;return;}auto id=metadata.at("id").get<std::string>();metadata["parent"]=metadata.at("parents").at(0);metadata["data"]=data;metadata["appProperties"]=Json::object();{std::lock_guard guard(mutex);check(files.contains(metadata["parent"].get<std::string>()),"visible object escaped repository folder");if(files.contains(id)){out.status=409;return;}files[id]=metadata;}++uploads;out.status=201;out.set_content(Json{{"id",id}}.dump(),"application/json");});
        server.Get(R"(/drive/v3/files/(visible[0-9]+))",[&](const auto& in,auto& out){std::lock_guard guard(mutex);auto id=in.matches[1].str();if(!files.contains(id)){out.status=404;return;}const Json& file=files.at(id);if(in.get_param_value("alt")=="media"){++downloads;out.set_content(file.at("data").get<std::string>(),"application/octet-stream");}else out.set_content(Json{{"id",id},{"mimeType",file.at("mimeType")},{"spaces",Json::array({"drive"})},{"appProperties",file.at("appProperties")},{"trashed",false}}.dump(),"application/json");});
        auto port=server.bind_to_any_port("127.0.0.1");check(port>0,"fixture bind failed");origin="http://127.0.0.1:"+std::to_string(port);worker=std::jthread([&]{server.listen_after_bind();});server.wait_until_ready();}
    ~Fixture(){server.stop();}
};
int main(int argc,char** argv){try{auto base=fs::absolute(cxs::path(argc>1?argv[1]:"visible-contracts"))/cxs::random_id();auto state=base/"state",source=base/"source",config_file=base/"config.json";cxs::private_directory(source);cxs::write_atomic(source/"sample.txt",Bytes{'v','i','s','i','b','l','e'});Fixture fixture;cxs::Key key;key.fill(0xaa);Json secrets={{"key_hex",std::string(64,'a')}};
    Json config={{"format",1},{"device",cxs::random_id()},{"state",cxs::utf8(state)},{"roots",Json::array({{{"id","fixture"},{"path",cxs::utf8(source)}}})},{"remote",{{"provider","google_drive"},{"storage_mode","visible"},{"repository","default"},{"client_id","fixture.apps.googleusercontent.com"},{"allow_loopback_http",true},{"test_api_origin",fixture.origin},{"test_token_origin",fixture.origin}}}};
    auto credentials=[&](const fs::path& directory,const std::string& scope){auto current=config;current["state"]=cxs::utf8(directory);cxs::write_atomic(cxs::google_credential_path(current),cxs::seal(encoded(Json{{"client_id","fixture.apps.googleusercontent.com"},{"refresh_token","visible-refresh"},{"scope",scope}}),key,"google-oauth-v1"));};
    credentials(state,"https://www.googleapis.com/auth/drive.appdata");bool rejected=false;try{cxs::GoogleDrive drive(config,secrets);}catch(...){rejected=true;}check(rejected&&fixture.folders==0,"appdata-only credentials expanded visible access");credentials(state,"https://www.googleapis.com/auth/drive.file");cxs::write_atomic(config_file,encoded(config));auto request=[&](const std::string& op){auto value=secrets;value["op"]=op;value["config"]=cxs::utf8(config_file);return value;};
    fixture.fail_snapshots=true;rejected=false;try{cxs::execute(request("backup"));}catch(...){rejected=true;}check(rejected&&fixture.uploads==1&&fixture.folders==2,"visible fixture did not preserve captured upload before failed commit");
    auto count=fixture.uploads.load();fs::rename(source,base/"retained-source");fixture.fail_snapshots=false;auto resumed=cxs::execute(request("resume"));check(resumed.at("body_bytes")==0&&resumed.at("metadata_checked")==0&&resumed.at("resumed_objects")==1&&fixture.uploads==count+1,"visible resume re-read source or duplicated confirmed object");auto folder=resumed.at("storage").at("folder_id").get<std::string>();check(!folder.empty()&&resumed.at("storage").at("folder_url")=="https://drive.google.com/drive/folders/"+folder,"visible folder link missing");
    config["state"]=cxs::utf8(base/"empty-state");config["remote"]["folder_id"]=folder;credentials(base/"empty-state","https://www.googleapis.com/auth/drive.file");cxs::write_atomic(config_file,encoded(config));auto restore=request("restore");restore["snapshot"]=resumed.at("snapshot");restore["output"]=cxs::utf8(base/"restored");cxs::execute(restore);check(cxs::read_bytes(base/"restored/fixture/sample.txt")==Bytes({'v','i','s','i','b','l','e'})&&fixture.downloads>=2,"empty-cache visible restore did not fetch real objects");
    auto report=Json{{"ok",true},{"resume",resumed},{"empty_cache_restore",true},{"scope_rejection",true},{"folders",fixture.folders.load()},{"uploads",fixture.uploads.load()},{"downloads",fixture.downloads.load()}};cxs::write_atomic(base/"report.json",encoded(report));std::cout<<"VISIBLE_DRIVE_CONTRACTS_PASS: minimal scope, durable folder ID, no hidden-space writes, failed commit resume, empty-cache restore\nEvidence: "<<cxs::utf8(base/"report.json")<<'\n';return 0;
}catch(const std::exception& e){std::cerr<<"VISIBLE_DRIVE_CONTRACTS_FAIL: "<<e.what()<<'\n';return 1;}}
