#include "encryption.hpp"
#include <sodium.h>
#include <fstream>
namespace cxs {
namespace {
constexpr size_t block_size=1024*1024;
struct WipedKey{Key value{};~WipedKey(){sodium_memzero(value.data(),value.size());}};
void derive(WipedKey& key,const std::string& password,const unsigned char* salt){if(password.empty())throw std::runtime_error("this master key requires its password");if(crypto_pwhash(key.value.data(),key.value.size(),password.data(),password.size(),salt,crypto_pwhash_OPSLIMIT_INTERACTIVE,crypto_pwhash_MEMLIMIT_INTERACTIVE,crypto_pwhash_ALG_ARGON2ID13))throw std::runtime_error("cannot derive master-key password protection");}
}
bool encrypt_entry(const Json& config,const Json& entry){auto mode=config.value("payload_mode",std::string("encrypted"));if(mode=="encrypted")return true;if(mode=="original")return false;auto root=entry.at("root").get<std::string>(),relative=entry.at("path").get<std::string>();auto base=relative.ends_with("-wal")?relative.substr(0,relative.size()-4):relative.ends_with("-journal")?relative.substr(0,relative.size()-8):relative;for(const auto& rule:config.value("encryption_rules",Json::array())){if(rule.at("root")!=root)continue;auto selected=rule.at("path").get<std::string>();if(selected.empty()||relative==selected||base==selected||relative.starts_with(selected+"/"))return true;}return false;}
Bytes protect_key(const Key& key,const std::string& password){Bytes result={'C','X','S','K','E','Y','2','\n'};result.resize(8+crypto_pwhash_SALTBYTES);randombytes_buf(result.data()+8,crypto_pwhash_SALTBYTES);WipedKey derived;derive(derived,password,result.data()+8);auto wrapped=seal(Bytes(key.begin(),key.end()),derived.value,"local-master-key-v2");result.insert(result.end(),wrapped.begin(),wrapped.end());return result;}
Key unprotect_key(const Bytes& data,const std::string& password){if(data.size()!=8+crypto_pwhash_SALTBYTES+32+44)throw std::runtime_error("invalid password-protected master key");WipedKey derived;derive(derived,password,data.data()+8);auto plain=open(Bytes(data.begin()+8+crypto_pwhash_SALTBYTES,data.end()),derived.value,"local-master-key-v2");Key key{};std::copy(plain.begin(),plain.end(),key.begin());sodium_memzero(plain.data(),plain.size());return key;}
void protect_file(const fs::path& input,const fs::path& output,const Key& key){std::ifstream in(input,std::ios::binary);std::ofstream out(output,std::ios::binary|std::ios::trunc);if(!in||!out)throw std::runtime_error("cannot open selective encryption staging file");crypto_secretstream_xchacha20poly1305_state state;unsigned char header[crypto_secretstream_xchacha20poly1305_HEADERBYTES];crypto_secretstream_xchacha20poly1305_init_push(&state,header,key.data());out.write("CXSFILE1",8);out.write(reinterpret_cast<char*>(header),sizeof header);Bytes plain(block_size),cipher(block_size+crypto_secretstream_xchacha20poly1305_ABYTES);for(;;){in.read(reinterpret_cast<char*>(plain.data()),plain.size());auto n=in.gcount();if(in.bad())throw std::runtime_error("cannot read selective encryption input");bool final=in.peek()==std::char_traits<char>::eof();unsigned long long length=0;crypto_secretstream_xchacha20poly1305_push(&state,cipher.data(),&length,plain.data(),n,nullptr,0,final?crypto_secretstream_xchacha20poly1305_TAG_FINAL:0);unsigned char size[4];for(int i=0;i<4;++i)size[i]=static_cast<unsigned char>(length>>(i*8));out.write(reinterpret_cast<char*>(size),4);out.write(reinterpret_cast<char*>(cipher.data()),length);if(final)break;}out.flush();sodium_memzero(plain.data(),plain.size());sodium_memzero(&state,sizeof state);if(!out)throw std::runtime_error("cannot flush selectively encrypted file");}
void unprotect_file(const fs::path& input,const fs::path& output,const Key& key){std::ifstream in(input,std::ios::binary);std::ofstream out(output,std::ios::binary|std::ios::trunc);char magic[8];unsigned char header[crypto_secretstream_xchacha20poly1305_HEADERBYTES];if(!in||!out||!in.read(magic,8)||std::string(magic,8)!="CXSFILE1"||!in.read(reinterpret_cast<char*>(header),sizeof header))throw std::runtime_error("invalid selectively encrypted file");crypto_secretstream_xchacha20poly1305_state state;if(crypto_secretstream_xchacha20poly1305_init_pull(&state,header,key.data()))throw std::runtime_error("invalid selective encryption header");Bytes plain(block_size),cipher(block_size+crypto_secretstream_xchacha20poly1305_ABYTES);bool final=false;while(!final){unsigned char size[4];if(!in.read(reinterpret_cast<char*>(size),4))throw std::runtime_error("truncated selectively encrypted file");uint32_t length=0;for(int i=0;i<4;++i)length|=uint32_t(size[i])<<(i*8);if(length<crypto_secretstream_xchacha20poly1305_ABYTES||length>cipher.size()||!in.read(reinterpret_cast<char*>(cipher.data()),length))throw std::runtime_error("invalid selective encryption block");unsigned long long n=0;unsigned char tag=0;if(crypto_secretstream_xchacha20poly1305_pull(&state,plain.data(),&n,&tag,cipher.data(),length,nullptr,0))throw std::runtime_error("authentication failed: damaged selectively encrypted file or wrong key");out.write(reinterpret_cast<char*>(plain.data()),n);final=tag==crypto_secretstream_xchacha20poly1305_TAG_FINAL;}if(in.peek()!=std::char_traits<char>::eof())throw std::runtime_error("unexpected data after selective encryption final block");out.flush();sodium_memzero(plain.data(),plain.size());sodium_memzero(&state,sizeof state);if(!out)throw std::runtime_error("cannot flush decrypted file");}
}
