#include "google_drive.hpp"
#include <sodium.h>
namespace cxs {
namespace {
Bytes encode_original(const Json& value){auto text=value.dump();return {text.begin(),text.end()};}
Json parse_original(const Response& response){if(response.status<200||response.status>=300)throw std::runtime_error("Google original-file request failed: HTTP "+std::to_string(response.status));return Json::parse(response.body.begin(),response.body.end());}
std::string quote_original(const std::string& text){std::string result;for(auto c:text){if(c=='\\'||c=='\'')result+='\\';result+=c;}return result;}
}
std::vector<Json> GoogleDrive::original_query(const std::string& parent,const std::string& expression){std::vector<Json> result;std::set<std::string> seen;std::string token;do{auto url=origin_+"/drive/v3/files?spaces="+(storage_mode_=="visible"?"drive":"appDataFolder")+"&pageSize=1000&fields="+url_encode("nextPageToken,incompleteSearch,files(id,name,appProperties)")+"&q="+url_encode("trashed = false and '"+quote_original(parent)+"' in parents and ("+expression+")");if(!token.empty())url+="&pageToken="+url_encode(token);auto value=parse_original(call(url,"GET"));if(value.value("incompleteSearch",false))throw std::runtime_error("incomplete original-file folder listing");for(auto& item:value.at("files"))result.push_back(item);token=value.value("nextPageToken",std::string());if(!token.empty()&&!seen.insert(token).second)throw std::runtime_error("repeated original-file listing page");if(result.size()>100000)throw std::runtime_error("original-file listing safety limit");}while(!token.empty());return result;}
std::string GoogleDrive::original_folder(const std::string& relative,bool create){if(auto found=original_folders_.find(relative);found!=original_folders_.end())return found->second;std::string parent,leaf,expression;if(relative.empty()){parent=storage_mode_=="visible"?visible_folder(create):"appDataFolder";if(parent.empty())return {};leaf="Original files";expression="appProperties has { key='cxs_original_repo' and value='"+prefix_+"' } and mimeType='application/vnd.google-apps.folder'";}else{auto value=path(relative);auto ancestor=utf8(value.parent_path());leaf=utf8(value.filename());if(leaf.empty()||leaf=="."||leaf==".."||value.is_absolute())throw std::runtime_error("invalid original-file folder path");parent=original_folder(ancestor,create);if(parent.empty())return {};expression="name = '"+quote_original(leaf)+"' and mimeType='application/vnd.google-apps.folder'";}auto candidates=original_query(parent,expression);std::string id;for(const auto& candidate:candidates){auto next=candidate.at("id").get<std::string>();if(id.empty()||next<id)id=next;}if(id.empty()&&create){auto metadata=Json{{"name",leaf},{"mimeType","application/vnd.google-apps.folder"},{"parents",Json::array({parent})},{"appProperties",{{"cxs_original_repo",prefix_}}}};id=parse_original(call(origin_+"/drive/v3/files?fields=id","POST",encode_original(metadata),{"Content-Type: application/json; charset=UTF-8"})).at("id");}if(!id.empty()){if(id.size()>200||!std::all_of(id.begin(),id.end(),[](unsigned char c){return std::isalnum(c)||c=='-'||c=='_';}))throw std::runtime_error("invalid original folder ID");original_folders_[relative]=id;}return id;}
std::string GoogleDrive::original_find(const std::string& relative,const std::string& hash){auto value=path(relative);auto parent=original_folder(utf8(value.parent_path()),false);if(parent.empty())return {};auto leaf=utf8(value.filename());auto candidates=original_query(parent,"name = '"+quote_original(leaf)+"' and mimeType != 'application/vnd.google-apps.folder'");std::string id;for(const auto& item:candidates){if(item.at("name")!=leaf)continue;if(!hash.empty()&&item.value("appProperties",Json::object()).value("cxs_hash",std::string())!=hash)throw std::runtime_error("original-file retry hash mismatch");auto next=item.at("id").get<std::string>();if(id.empty()||next<id)id=next;}return id;}
Response GoogleDrive::original_get(const std::string& relative,const fs::path& download){auto id=original_find(relative);if(id.empty())return {404,{},{}};return call(origin_+"/drive/v3/files/"+id+"?alt=media","GET",{}, {},{},download);}
std::vector<std::string> GoogleDrive::original_list(const std::string& relative){auto parent=original_folder(relative,false);if(parent.empty())return {};std::vector<std::string> result;for(const auto& item:original_query(parent,"mimeType != 'application/vnd.google-apps.folder'"))result.push_back(item.at("name"));return result;}
bool GoogleDrive::original_upload(const std::string& relative,const fs::path& file,const std::string& hash){if(!original_find(relative,hash).empty())return false;auto value=path(relative);auto parent=original_folder(utf8(value.parent_path()),true);auto id=upload_id();auto metadata=Json{{"id",id},{"name",utf8(value.filename())},{"mimeType","application/octet-stream"},{"parents",Json::array({parent})},{"appProperties",{{"cxs_hash",hash}}}};auto session=call(origin_+"/upload/drive/v3/files?uploadType=resumable&fields=id","POST",encode_original(metadata),{"Content-Type: application/json; charset=UTF-8","X-Upload-Content-Type: application/octet-stream","X-Upload-Content-Length: "+std::to_string(fs::file_size(file))});if(session.status<200||session.status>=300)throw std::runtime_error("Google original upload initiation failed: HTTP "+std::to_string(session.status));if(!session.location.starts_with(origin_+"/upload/drive/v3/files?")||session.location.find_first_of("\r\n#")!=std::string::npos)throw std::runtime_error("untrusted original-file upload session");auto uploaded=parse_original(call(session.location,"PUT",{},{"Content-Type: application/octet-stream"},file));if(uploaded.at("id")!=id)throw std::runtime_error("original-file upload ID mismatch");return true;}
bool GoogleDrive::original_copy(const std::string& from,const std::string& to,const std::string& hash){if(!original_find(to,hash).empty())return true;auto source=original_find(from,hash);if(source.empty())return false;auto value=path(to);auto parent=original_folder(utf8(value.parent_path()),true);auto metadata=Json{{"name",utf8(value.filename())},{"parents",Json::array({parent})},{"appProperties",{{"cxs_hash",hash}}}};parse_original(call(origin_+"/drive/v3/files/"+source+"/copy?fields=id","POST",encode_original(metadata),{"Content-Type: application/json; charset=UTF-8"}));return true;}
bool GoogleDrive::original_metadata(const std::string& relative,const Bytes& data){if(!original_find(relative).empty())return false;auto file=state_/"scratch"/(random_id()+".json");write_atomic(file,data);try{auto result=original_upload(relative,file,digest(data,folder_key_));fs::remove(file);return result;}catch(...){std::error_code error;fs::remove(file,error);throw;}}
}
