#include "transfer_engine.hpp"
#include "operation_runtime.hpp"
#include "encryption.hpp"
#include <fstream>
namespace cxs {
namespace {struct TemporaryOriginal{fs::path plain,protected_file;~TemporaryOriginal(){std::error_code error;fs::remove(plain,error);fs::remove(protected_file,error);}};}
Json TransferEngine::publish_original(Json manifest,const Json& parents,SnapshotJob* job){auto& runtime=runtime_;auto& store=runtime.store;if(!job)throw std::runtime_error("original-file backup requires a prepared job");store.ensure();auto id=job->data.at("snapshot").get<std::string>();Json previous;
    if(job->data.contains("commit_manifest"))manifest=job->data.at("commit_manifest");
    else{manifest["snapshot"]=id;manifest["device"]=runtime.config.at("device");manifest["created_unix"]=unix_now();manifest["committed_unix"]=manifest["created_unix"];manifest["parents"]=parents;manifest["payload_mode"]=runtime.config.at("payload_mode");if(job->data.contains("previous_snapshot"))manifest["parents"].push_back(job->data.at("previous_snapshot"));std::set<std::string> paths;for(auto& entry:manifest["entries"]){entry["encrypted"]=entry.value("kind",std::string())=="file"&&encrypt_entry(runtime.config,entry);auto relative="files/"+id+"/"+entry.at("root").get<std::string>()+"/"+entry.at("path").get<std::string>();if(entry.at("encrypted").get<bool>())relative+=".cxs";if(!paths.insert(relative).second)throw std::runtime_error("selected encryption creates a filename collision; choose a different scope");entry["original_path"]=relative;}job->data["commit_manifest"]=manifest;job->save();}
    if(job->data.contains("previous_snapshot"))previous=snapshot(job->data.at("previous_snapshot"));
    uint64_t count=0,size=0;for(const auto& entry:manifest.at("entries"))if(entry.at("kind")=="file"){++count;size+=entry.at("bytes").get<uint64_t>();}begin_progress("uploading",count,count,size);
    for(const auto& [name,entry]:manifest.at("entries").items()){checkpoint();auto remote=entry.at("original_path").get<std::string>();if(entry.at("kind")=="directory"){store.original_directory(remote);continue;}const auto receipt=digest(bytes(Json{{"path",remote},{"hash",entry.at("hash")}}),runtime.key.value);auto logical=entry.at("bytes").get<uint64_t>();if(job->confirmed(receipt)){++runtime.resumed_objects;advance_progress(1,1,logical);continue;}
        bool copied=false;if(!previous.empty()&&previous.at("entries").contains(name)){const auto& old=previous.at("entries").at(name);if(old.at("hash")==entry.at("hash")&&old.value("encrypted",false)==entry.at("encrypted").get<bool>())copied=store.original_copy(old.at("original_path"),remote,entry.at("hash"));}
        bool uploaded=false;uint64_t transmitted=0;if(!copied){TemporaryOriginal staged{runtime.state/"scratch"/(random_id()+".original"),runtime.state/"scratch"/(random_id()+".protected")};std::ofstream out(staged.plain,std::ios::binary|std::ios::trunc);if(!out)throw std::runtime_error("cannot stage prepared original file");crypto_generichash_state hash;crypto_generichash_init(&hash,runtime.key.value.data(),runtime.key.value.size(),32);uint64_t total=0;for(const auto& chunk:entry.at("chunks")){checkpoint();auto object=chunk.get<std::string>();auto plain=open(read_bytes(cache(object),chunk_size+128),runtime.key.value,"object:"+object);if(digest(plain,runtime.key.value)!=object)throw std::runtime_error("prepared original cache digest mismatch");out.write(reinterpret_cast<const char*>(plain.data()),plain.size());crypto_generichash_update(&hash,plain.data(),plain.size());total+=plain.size();sodium_memzero(plain.data(),plain.size());}out.flush();if(!out)throw std::runtime_error("cannot flush prepared original file");out.close();unsigned char digest_value[32];crypto_generichash_final(&hash,digest_value,32);char encoded[65];sodium_bin2hex(encoded,sizeof encoded,digest_value,sizeof digest_value);if(total!=logical||entry.at("hash")!=encoded)throw std::runtime_error("prepared original file digest mismatch");auto upload=staged.plain;if(entry.at("encrypted").get<bool>()){auto durable=runtime.state/"jobs"/job->data.at("job_id").get<std::string>()/"protected"/(receipt+".cxs");private_directory(durable.parent_path());if(!fs::exists(durable)){protect_file(staged.plain,staged.protected_file,runtime.key.value);fs::rename(staged.protected_file,durable);}else unprotect_file(durable,staged.protected_file,runtime.key.value);upload=durable;}uploaded=store.original_upload(remote,upload,entry.at("hash"));if(uploaded)transmitted=fs::file_size(upload);}
        job->confirm(receipt);if(uploaded&&!transmitted){std::lock_guard guard(runtime.progress_mutex);++runtime.uploaded;}advance_progress(1,1,logical,transmitted);
    }
    checkpoint();phase_progress("committing");auto payload=bytes(manifest);if(!store.put_immutable("snapshots/"+id+".json",payload)&&snapshot(id)!=manifest)throw std::runtime_error("original snapshot commit mismatch");return manifest;
}
}
